import Layout from "@/components/Layout";
export const metadata = {
  title: 'Code MERN',
  description: 'Generated by create next app',
}

export default function CodemernLayout({ children }) {
  return <>{children}</> 
}
